management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always   
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
  jpa:
    database-platform:  org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8761/eureka
myapp:
   title: "stage"
store:
  storeNo: 6
  storeName: Medplus Pharmacy
  owner: Yuvaraj
  openHours: 9
  openMinutes: 20
  closeHours: 11
  closeMinutes: 30 